### ISSUE TITLE
Initial switch state not detected on startup

### ISSUE THREAD

**Issue by HED-mstarr** [gandro/input-event-daemon#5]
When input-event-daemon is started, it does not detect the initial switch state.  This is useful since the application allows assigning events to both states of a switch, unlike a key press.  I have made the following patch to implement switch events based on initial switch states if you would add this to the code:

--- input-event-daemon-v0.1.3-orig/input-event-daemon.c 2015-03-11 13:12:20.290530200 -0500
+++ input-event-daemon-v0.1.3/input-event-daemon.c      2015-03-11 13:11:04.197242704 -0500
@@ -634,8 +634,9 @@ void daemon_init() {
 }
 
 void daemon_start_listener() {
-    int i, select_r, fd_len;
+    int i, n, select_r, fd_len;
     unsigned long tms_start, tms_end, idle_time = 0;
+    unsigned char sw_states[SW_MAX/8 + 1];
     fd_set fdset, initial_fdset;
     struct input_event event;
     struct timeval tv, tv_start, tv_end;
@@ -653,6 +654,14 @@ void daemon_start_listener() {
             exit(EXIT_FAILURE);
         }
         FD_SET(conf.listen_fd[i], &initial_fdset);
+        ioctl(conf.listen_fd[i], EVIOCGSW(sizeof sw_states), &sw_states);
+        for (n=0; n < SW_MAX; n++) {
+            memset(&event, '\0', sizeof(event));
+            event.type = EV_SW;
+            event.code = n;
+            event.value = (sw_states[n/8] >> n%8) & 0x1;
+            input_parse_event(&event, conf.listen[i]);
+        }
     }
 
     fd_len = i;

**Comment by gandro** [comment]
Thanks, looks good to me. Please note however that I am not really maintaining this project anymore.

To anybody who wishes to add features or bug fixes (as there a few known bugs): Feel free to fork this project.
